apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: KUBERNETES-NAMESPACE
  labels:
    app: geoserver
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
      component: rabbitmq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geoserver
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.11-management
        imagePullPolicy: "IfNotPresent"
        name: rabbitmq
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            cpu: "1500m"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
        - mountPath: /mnt/volumes/statics
          name: statics
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data
      - name: statics
        persistentVolumeClaim:
          claimName: statics
status: {}
